# Setup
title:               Jae Hyun Lee
tagline:             'UVA School of Data Science'
description:         ''
url:                 https://jaeh-lee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jae Hyun Lee
  url:               https://jaeh-lee.github.io
  email:             jl3fp@virginia.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
